import {
  FaCircleCheck,
  FaCircleXmark,
  FaPencil,
  FaTrash,
  FaGear,
  FaHouse,
  FaFileExport,
  FaBell,
  FaLock,
  FaLockOpen,
  FaChevronDown,
  FaChevronUp,
  FaSpinner,
  FaPlus,
  FaMinus,
  FaEye,
  FaEyeSlash,
  FaCheck,
  FaXmark,
  FaArrowRight,
  FaCopy,
  FaPause,
  FaPlay,
  FaDownload,
  FaCalendar,
  FaUser,
  FaEnvelope,
  FaPhone,
  FaMapPin,
  FaLink,
  FaShield,
  FaCloudArrowUp,
  FaImage,
  FaCircleQuestion,
  FaBars,
  FaList,
  FaInbox,
  FaChartLine,
  FaBuilding,
  FaClipboardList,
  FaPalette,
  FaMagnifyingGlass,
  FaFilePen,
  FaFolderOpen,
  FaListCheck,
  FaTicket,
  FaArrowLeft,
  FaSackDollar,
  FaClapperboard,
  FaBolt,
  FaBullseye,
  FaUsers,
  FaTrophy,
  FaClock,
  FaFileContract,
} from 'react-icons/fa6';

export const VitaIcons = {
  success: FaCircleCheck,
  error: FaCircleXmark,
  edit: FaPencil,
  delete: FaTrash,
  settings: FaGear,
  home: FaHouse,
  export: FaFileExport,
  notification: FaBell,
  lock: FaLock,
  unlock: FaLockOpen,
  expand: FaChevronDown,
  collapse: FaChevronUp,
  loading: FaSpinner,
  add: FaPlus,
  remove: FaMinus,
  eye: FaEye,
  eyeSlash: FaEyeSlash,
  check: FaCheck,
  times: FaXmark,
  arrow: FaArrowRight,
  copy: FaCopy,
  pause: FaPause,
  play: FaPlay,
  download: FaDownload,
  calendar: FaCalendar,
  user: FaUser,
  envelope: FaEnvelope,
  phone: FaPhone,
  mapPin: FaMapPin,
  link: FaLink,
  gear: FaGear,
  shield: FaShield,
  upload: FaCloudArrowUp,
  image: FaImage,
  question: FaCircleQuestion,
  menu: FaBars,
  list: FaList,
  inbox: FaInbox,
  chart: FaChartLine,
  building: FaBuilding,
  close: FaXmark,
  cog: FaGear,
  users: FaUser,
  survey: FaClipboardList,
  palette: FaPalette,
  search: FaMagnifyingGlass,
  document: FaFilePen,
  folder: FaFolderOpen,
  checklist: FaListCheck,
  ticket: FaTicket,
  back: FaArrowLeft,
  money: FaSackDollar,
  film: FaClapperboard,
  bolt: FaBolt,
  target: FaBullseye,
  team: FaUsers,
  trophy: FaTrophy,
  clock: FaClock,
  contract: FaFileContract,
};

export type VitaIconName = keyof typeof VitaIcons;
