import { useEffect, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../core/api';
import { LoadingSpinner } from '../../shared/LoadingSpinner';
import { triggerToast } from '../../shared/toast-events';
import { QueryErrorState } from '../../shared/QueryErrorState';
import type { ReservationForm } from './types';
import { localInputToUtc, utcToLocalInput } from './local-time';
import './ReservationOperationsPage.css';

/** Reglas que no pertenecen al constructor guiado: no duplica diseño, horario, cupos ni publicación. */
export function ReservationLocalConfigPage() {
  const { id = '' } = useParams();
  const location = useLocation();
  const clientMode = location.pathname.startsWith('/portal/');
  const base = clientMode ? '/portal/reservations' : '/reservations';
  const qc = useQueryClient();
  const { data: local, isLoading, error, refetch } = useQuery<ReservationForm>({ queryKey: ['reservation-local', id], queryFn: () => api.get(`/reservations/forms/${id}`), enabled: Boolean(id) });
  const [draft, setDraft] = useState<ReservationForm | null>(null);
  useEffect(() => { if (local) setDraft(local); }, [local]);
  // Los accesos rapidos enlazan a un bloque concreto: sin esto el ancla llega antes de que
  // exista la seccion, porque el formulario se pinta recien cuando responde la consulta.
  useEffect(() => {
    if (!draft || !location.hash) return;
    document.getElementById(location.hash.slice(1))?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }, [draft, location.hash]);
  const update = (patch: Partial<ReservationForm>) => setDraft((current) => current ? { ...current, ...patch } : current);
  const design = (key: string, value: string) => update({ designConfig: { ...draft?.designConfig, [key]: value } });
  const save = useMutation({ mutationFn: () => api.patch<ReservationForm>(`/reservations/forms/${id}`, { designConfig: draft?.designConfig, resourcesConfig: draft?.resourcesConfig, teamNotifications: draft?.teamNotifications, calendarEnabled: draft?.calendarEnabled }), onSuccess: (next) => { setDraft(next); qc.setQueryData(['reservation-local', id], next); qc.setQueryData(['reservation-form', id], next); void qc.invalidateQueries({ queryKey: ['reservation-locals'] }); triggerToast('Cambios guardados'); } });
  if (isLoading || !draft) return <LoadingSpinner text="Abriendo ajustes especiales..." />;
  if (error) return <QueryErrorState message={error.message} onRetry={() => void refetch()} />;
  const zones = draft.resourcesConfig ?? [];
  const setZones = (next: NonNullable<ReservationForm['resourcesConfig']>) => update({ resourcesConfig: next });
  const updateZone = (index: number, patch: Partial<NonNullable<ReservationForm['resourcesConfig']>[number]>) => setZones(zones.map((zone, current) => current === index ? { ...zone, ...patch } : zone));
  const addZone = () => setZones([...zones, { id: `zona-${Date.now()}`, name: '', capacity: draft.capacityPerSlot, description: '', smokingAllowed: false }]);
  const teamEmails = (draft.teamNotifications || []).join(', ');
  const setBookingPause = (value: string) => {
    try { design('bookingPausedUntil', value ? localInputToUtc(value, draft.timezone) : ''); }
    catch { triggerToast('Selecciona una hora válida para la zona del local.', 'error'); }
  };

  return <main className="page reservation-operations-page">
    <header className="reservation-operations-hero"><div><Link to={`${base}/locals/${id}`} className="back-link">← Volver al local</Link><span className="page-eyebrow">ZONAS, AVISOS Y TEXTOS LEGALES</span><h1>{draft.name}</h1><p className="page-subtitle">Lo que no entra en el recorrido guiado: ninguna de estas opciones se repite allá.</p>{save.isSuccess && <small className="save-status">Todos los cambios están guardados.</small>}</div><div className="portal-item-actions"><Link className="btn btn-outline" to={`${base}/forms/${id}/design`}>Configuración guiada</Link><button className="btn btn-primary" type="button" disabled={save.isPending} onClick={() => save.mutate()}>{save.isPending ? 'Guardando...' : 'Guardar cambios'}</button></div></header>
    <section className="reservation-readiness"><div><span className="page-eyebrow">RESPONSABLE Y CONTACTO</span><h2>Información visible para quien reserva</h2></div><div className="form-row"><label>Razón social o responsable<input className="input" value={String(draft.designConfig?.legalCompanyName || '')} onChange={(e) => design('legalCompanyName', e.target.value)} /></label><label>RUT / identificador<input className="input" value={String(draft.designConfig?.legalCompanyId || '')} onChange={(e) => design('legalCompanyId', e.target.value)} /></label><label>Correo de soporte<input className="input" type="email" value={String(draft.designConfig?.supportEmail || '')} onChange={(e) => design('supportEmail', e.target.value)} /></label></div><div className="form-row"><label>WhatsApp del local<input className="input" value={String(draft.designConfig?.whatsappBusinessNumber || '')} onChange={(e) => design('whatsappBusinessNumber', e.target.value)} placeholder="+56 9 1234 5678" /></label><label>Mensaje para grupos<textarea className="input" value={String(draft.designConfig?.whatsappGroupMessage || '')} onChange={(e) => design('whatsappGroupMessage', e.target.value)} /></label></div><div className="form-row"><label>URL de privacidad<input className="input" type="url" value={String(draft.designConfig?.privacyUrl || '')} onChange={(e) => design('privacyUrl', e.target.value)} placeholder="https://..." /></label><label>URL de condiciones<input className="input" type="url" value={String(draft.designConfig?.termsUrl || '')} onChange={(e) => design('termsUrl', e.target.value)} placeholder="https://..." /></label></div><label>Política de cancelación visible<textarea className="input" value={String(draft.designConfig?.cancellationPolicy || '')} onChange={(e) => design('cancellationPolicy', e.target.value)} /></label></section>
    <section className="reservation-readiness"><div><span className="page-eyebrow">CORREOS Y CALENDARIO</span><h2>Avisos internos</h2></div><label>Correos del equipo<input className="input" value={teamEmails} onChange={(e) => update({ teamNotifications: e.target.value.split(/[,;\s]+/).map((email) => email.trim()).filter(Boolean) })} placeholder="reservas@local.cl, gerente@local.cl" /><small>Separa varios correos con coma. No se envía una prueba desde esta pantalla.</small></label><label className="toggle-row"><input type="checkbox" checked={Boolean(draft.calendarEnabled)} onChange={(e) => update({ calendarEnabled: e.target.checked })} /> Crear evento en el calendario conectado del local</label></section>
    <section className="reservation-readiness"><div><span className="page-eyebrow">CONSENTIMIENTOS</span><h2>Reserva y marketing</h2><p className="page-subtitle">Marketing es opcional y no condiciona la reserva.</p></div><label>Texto para gestionar la reserva<textarea className="input" value={String(draft.designConfig?.reservationConsentText || '')} onChange={(e) => design('reservationConsentText', e.target.value)} /></label><div className="form-row"><label>Texto opcional de marketing<textarea className="input" value={String(draft.designConfig?.marketingConsentText || '')} onChange={(e) => design('marketingConsentText', e.target.value)} /></label><label>Versión del consentimiento<input className="input" value={String(draft.designConfig?.marketingConsentVersion || 'mkt-v1')} onChange={(e) => design('marketingConsentVersion', e.target.value)} /></label></div></section>
    <section className="reservation-readiness" id="zonas"><div><span className="page-eyebrow">ZONAS Y PREFERENCIAS</span><h2>Terraza, salón y condiciones de visita</h2><p className="page-subtitle">Desactivar conserva la zona y su historial, pero deja de mostrarla para nuevas reservas.</p></div>{zones.map((zone, index) => <div className="reservation-zone-row" key={zone.id}><label>Nombre<input className="input" value={zone.name} onChange={(e) => updateZone(index, { name: e.target.value })} placeholder="Ej. Terraza" /></label><label>Cupo<input className="input" type="number" min="1" max="500" value={zone.capacity || draft.capacityPerSlot} onChange={(e) => updateZone(index, { capacity: Number(e.target.value) })} /></label><label>Descripción<input className="input" value={zone.description || ''} onChange={(e) => updateZone(index, { description: e.target.value })} /></label><label className="toggle-row"><input type="checkbox" checked={Boolean(zone.smokingAllowed)} onChange={(e) => updateZone(index, { smokingAllowed: e.target.checked })} /> Fumadores</label><label className="toggle-row"><input type="checkbox" checked={zone.active !== false} onChange={(e) => updateZone(index, { active: e.target.checked })} /> Disponible para reservar</label><button type="button" className="btn btn-outline btn-sm" onClick={() => updateZone(index, { active: zone.active === false })}>{zone.active === false ? 'Activar' : 'Desactivar'}</button></div>)}<button type="button" className="btn btn-outline btn-sm" onClick={addZone}>Agregar zona</button><div className="form-row"><label className="toggle-row"><input type="checkbox" checked={draft.designConfig?.askChildren === 'true'} onChange={(e) => design('askChildren', String(e.target.checked))} /> Niños / silla infantil</label><label className="toggle-row"><input type="checkbox" checked={draft.designConfig?.askAccessibility === 'true'} onChange={(e) => design('askAccessibility', String(e.target.checked))} /> Accesibilidad</label><label className="toggle-row"><input type="checkbox" checked={draft.designConfig?.askAllergies === 'true'} onChange={(e) => design('askAllergies', String(e.target.checked))} /> Restricciones alimentarias</label></div></section>
    <section className="reservation-readiness"><div><span className="page-eyebrow">CIERRE DEL TURNO</span><h2>Asistencia automática</h2></div><div className="form-row"><label className="toggle-row"><input type="checkbox" checked={draft.designConfig?.autoCloseAttendance !== 'false'} onChange={(e) => design('autoCloseAttendance', String(e.target.checked))} /> Cerrar asistencia automáticamente</label><label>Margen posterior (min)<input className="input" type="number" min="15" max="1440" disabled={draft.designConfig?.autoCloseAttendance === 'false'} value={String(draft.designConfig?.autoCloseAfterMinutes || '60')} onChange={(e) => design('autoCloseAfterMinutes', e.target.value)} /></label></div></section>
    <section className="reservation-readiness" id="pausa"><div><span className="page-eyebrow">PAUSA TEMPORAL</span><h2>Detener nuevas reservas</h2><p className="page-subtitle">La página pública no ofrecerá horarios hasta la fecha indicada. No elimina reservas ni despublica el local.</p></div><div className="form-row"><label>Reanudar automáticamente el<input className="input" type="datetime-local" value={utcToLocalInput(draft.designConfig?.bookingPausedUntil, draft.timezone)} onChange={(event) => setBookingPause(event.target.value)} /></label><label className="toggle-row"><input type="checkbox" checked={draft.designConfig?.enforceCompanyDailyCap !== 'false'} onChange={(event) => design('enforceCompanyDailyCap', String(event.target.checked))} /> Aplicar además el tope diario global de la empresa</label></div><button type="button" className="btn btn-outline btn-sm" disabled={!draft.designConfig?.bookingPausedUntil} onClick={() => design('bookingPausedUntil', '')}>Quitar pausa programada</button></section>
    <section className="reservation-readiness"><div><span className="page-eyebrow">OPERACIÓN AVANZADA</span><h2>Ritmo y grupos</h2></div><div className="form-row"><label>Tolerancia antes de no-show (min)<input className="input" type="number" min="0" value={String(draft.designConfig?.toleranceMinutes || '15')} onChange={(e) => design('toleranceMinutes', e.target.value)} /></label><label>Ritmo de llegadas (min)<input className="input" type="number" min="5" max="240" value={String(draft.designConfig?.slotCadenceMinutes || '15')} onChange={(e) => design('slotCadenceMinutes', e.target.value)} /></label><label>Retener cupo (min)<input className="input" type="number" min="1" max="30" value={String(draft.designConfig?.holdMinutes || '5')} onChange={(e) => design('holdMinutes', e.target.value)} /></label><label>Grupo grande desde<input className="input" type="number" min="2" max="100" value={String(draft.designConfig?.groupThreshold || '8')} onChange={(e) => design('groupThreshold', e.target.value)} /></label></div></section>
    {save.error && <div className="alert alert-error">No se pudieron guardar los cambios. Revisa los valores e inténtalo nuevamente.</div>}
  </main>;
}
